services:
  keep2dfilesbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: keep2dfilesbot:latest
    container_name: keep2dfilesbot
    restart: unless-stopped
    environment:
      DOTNET_ENVIRONMENT: Production
      BotConfiguration__Token: ${BOT_TOKEN:?BOT_TOKEN_REQUIRED}
      BotConfiguration__AllowedUsers__0: ${BOT_ALLOWED_USER_0:?BOT_ALLOWED_USER_0_REQUIRED}
      BotConfiguration__WorkingDirectory: ${BOT_WORKING_DIRECTORY:-/app/data}
      BotConfiguration__IsPublic: ${BOT_IS_PUBLIC:-false}
      DownloadConfiguration__MaxFileSize: ${DOWNLOAD_MAX_FILE_SIZE:-104857600}
      DownloadConfiguration__TimeoutSeconds: ${DOWNLOAD_TIMEOUT_SECONDS:-300}
      DownloadConfiguration__RetryCount: ${DOWNLOAD_RETRY_COUNT:-3}
      DownloadConfiguration__RetryDelaySeconds: ${DOWNLOAD_RETRY_DELAY_SECONDS:-2}
      StorageConfiguration__BasePath: ${STORAGE_BASE_PATH:-/app/data/files}
      StorageConfiguration__DateFormat: ${STORAGE_DATE_FORMAT:-yyyy-MM-dd}
      StorageConfiguration__SaveMetadata: ${STORAGE_SAVE_METADATA:-true}
    volumes:
      - bot_data:/app/data
      - bot_logs:/app/logs
    env_file:
      - .env

volumes:
  bot_data:
  bot_logs:
